FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

COPY main.go ./

COPY todo ./todo

COPY database ./database

RUN go mod download

RUN go build -o /docker-todo-go-grpc

EXPOSE 9090

CMD [ "/docker-todo-go-grpc" ]
