version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=119955
      - POSTGRES_DB=tododb
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data 
  server-go:
    image: grpc-todo/server:1.0
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '9090:9090'
  client-react:
    image: grpc-todo/react:1.0
    build: 
      context: .
      dockerfile: Dockerfile.react
    ports:
      - '3000:3000'
  envoy-proxy:
    image: grpc-todo/envoy:1.0
    build: 
      context: .
      dockerfile: Dockerfile.envoy
    network_mode: "host"
volumes:
  pgdata:
 