apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: grpc-todo/server:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-db
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30001