/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: pkg/user/user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as pkg_user_user_pb from '../../pkg/user/user_pb';


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddUser = new grpcWeb.MethodDescriptor(
    '/UserService/AddUser',
    grpcWeb.MethodType.UNARY,
    pkg_user_user_pb.UserAddRequest,
    pkg_user_user_pb.UserResponse,
    (request: pkg_user_user_pb.UserAddRequest) => {
      return request.serializeBinary();
    },
    pkg_user_user_pb.UserResponse.deserializeBinary
  );

  addUser(
    request: pkg_user_user_pb.UserAddRequest,
    metadata: grpcWeb.Metadata | null): Promise<pkg_user_user_pb.UserResponse>;

  addUser(
    request: pkg_user_user_pb.UserAddRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void): grpcWeb.ClientReadableStream<pkg_user_user_pb.UserResponse>;

  addUser(
    request: pkg_user_user_pb.UserAddRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/AddUser',
        request,
        metadata || {},
        this.methodDescriptorAddUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/AddUser',
    request,
    metadata || {},
    this.methodDescriptorAddUser);
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/UserService/GetUser',
    grpcWeb.MethodType.UNARY,
    pkg_user_user_pb.GetUserRequest,
    pkg_user_user_pb.UserResponses,
    (request: pkg_user_user_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    pkg_user_user_pb.UserResponses.deserializeBinary
  );

  getUser(
    request: pkg_user_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<pkg_user_user_pb.UserResponses>;

  getUser(
    request: pkg_user_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponses) => void): grpcWeb.ClientReadableStream<pkg_user_user_pb.UserResponses>;

  getUser(
    request: pkg_user_user_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponses) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorGetOneUser = new grpcWeb.MethodDescriptor(
    '/UserService/GetOneUser',
    grpcWeb.MethodType.UNARY,
    pkg_user_user_pb.GetOneUserResquest,
    pkg_user_user_pb.UserResponse,
    (request: pkg_user_user_pb.GetOneUserResquest) => {
      return request.serializeBinary();
    },
    pkg_user_user_pb.UserResponse.deserializeBinary
  );

  getOneUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null): Promise<pkg_user_user_pb.UserResponse>;

  getOneUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void): grpcWeb.ClientReadableStream<pkg_user_user_pb.UserResponse>;

  getOneUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/GetOneUser',
        request,
        metadata || {},
        this.methodDescriptorGetOneUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/GetOneUser',
    request,
    metadata || {},
    this.methodDescriptorGetOneUser);
  }

  methodDescriptorEditUser = new grpcWeb.MethodDescriptor(
    '/UserService/EditUser',
    grpcWeb.MethodType.UNARY,
    pkg_user_user_pb.GetOneUserResquest,
    pkg_user_user_pb.UserResponse,
    (request: pkg_user_user_pb.GetOneUserResquest) => {
      return request.serializeBinary();
    },
    pkg_user_user_pb.UserResponse.deserializeBinary
  );

  editUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null): Promise<pkg_user_user_pb.UserResponse>;

  editUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void): grpcWeb.ClientReadableStream<pkg_user_user_pb.UserResponse>;

  editUser(
    request: pkg_user_user_pb.GetOneUserResquest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: pkg_user_user_pb.UserResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/UserService/EditUser',
        request,
        metadata || {},
        this.methodDescriptorEditUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/UserService/EditUser',
    request,
    metadata || {},
    this.methodDescriptorEditUser);
  }

}

